language: csharp
solution: MetacoClient.sln

install:
  - nuget restore MetacoClient.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MetacoClient.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./MetacoClient.Tests/bin/Release/MetacoClient.Tests.dll


