language: csharp
solution: MetacoClient.sln

install:
  - nuget restore MetacoClient.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MetacoClient.sln
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.clr4.exe ./MetacoClient.Tests/bin/Release/MetacoClient.Tests.dll


