language: csharp
solution: MetacoClient.sln

install:
  - nuget restore MetacoClient.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MetacoClient.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MetacoClient.Tests/bin/Release/MetacoClient.Tests.dll

